package com.jj.androidenergyconsumer.notification

const val UNIVERSAL_NOTIFICATION_ID = 101
const val UNIVERSAL_NOTIFICATION_CHANNEL_ID = "UNIVERSAL_NOTIFICATION_CHANNEL_ID"
const val UNIVERSAL_NOTIFICATION_CHANNEL_NAME = "Universal notification"

const val BLUETOOTH_NOTIFICATION_ID = 102
const val BLUETOOTH_NOTIFICATION_CHANNEL_ID = "BLUETOOTH_NOTIFICATION_CHANNEL_ID"
const val BLUETOOTH_NOTIFICATION_CHANNEL_NAME = "Bluetooth notification"

const val CALCULATIONS_NOTIFICATION_ID = 103
const val CALCULATIONS_NOTIFICATION_CHANNEL_ID = "CALCULATIONS_NOTIFICATION_CHANNEL_ID"
const val CALCULATIONS_NOTIFICATION_CHANNEL_NAME = "Calculations notification"

const val GPS_NOTIFICATION_ID = 104
const val GPS_NOTIFICATION_CHANNEL_ID = "GPS_NOTIFICATION_CHANNEL_ID"
const val GPS_NOTIFICATION_CHANNEL_NAME = "GPS notification"

const val INTERNET_NOTIFICATION_ID = 105
const val INTERNET_NOTIFICATION_CHANNEL_ID = "INTERNET_NOTIFICATION_CHANNEL_ID"
const val INTERNET_NOTIFICATION_CHANNEL_NAME = "Internet notification"
