name: CI Debug artifact

on:
  push:
    tags:
      - '*d'

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Rename built artifact
        run: cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/AEC_debug_${{ github.run_number }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/debug/AEC_debug_${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}