name: Instrumentation tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
       # With Android P, instrumentation tests may use full power of inline instrumentation,
       # so object mocks, static mocks and mocking of final classes are supported.
       # Before Android P, only subclassing can be employed, so you will need the ‘all-open’ plugin.
        api-level: [29]
        target: [default, google_apis]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: ./gradlew connectedCheck